# V2.0 Framework Setup Script - Windows (Standalone Generator)
# Generated by /script command
# Run: .\setup-v2framework-win.ps1

$ErrorActionPreference = "Stop"
$TargetDir = "v2framework"

Write-Host "=== V2.0 Framework Setup (Windows) ===" -ForegroundColor Cyan

$scriptPath = $PSScriptRoot
$targetPath = Join-Path $scriptPath $TargetDir

if (Test-Path $targetPath) {
    Write-Host "Directory exists, removing..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $targetPath
}
Write-Host "Creating directory: $targetPath" -ForegroundColor Green
New-Item -ItemType Directory -Path $targetPath -Force | Out-Null

function Create-Dir {
    param([string]$path)
    $fullPath = Join-Path $targetPath $path
    New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
    Write-Host "  [Folder] Created: $path" -ForegroundColor DarkGray
}

function Create-File {
    param([string]$path, [string]$content)
    $fullPath = Join-Path $targetPath $path
    $parentDir = Split-Path $fullPath
    
    if (-not (Test-Path $parentDir)) {
        New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
    }
    
    $utf8NoBom = New-Object System.Text.UTF8Encoding $False
    [System.IO.File]::WriteAllText($fullPath, $content, $utf8NoBom)
    Write-Host "  [File]   Created: $path" -ForegroundColor Gray
}

Write-Host "`nGenerating Framework Structure..." -ForegroundColor Cyan

Create-Dir ".vibe\rules"
Create-Dir ".vibe\memory"
Create-Dir ".vibe\mcp_factory\template"
Create-Dir "docs\PRD"
Create-Dir "sandbox\test_environment"

Create-File ".vibe\memory\MEMORY_CORE.md" @"
# 长记忆 (Long-term Memory)

用于存储项目的核心知识和长期记忆。

---

## 2026-03-09 框架使用错误修正

### 错误描述
在创建 README.md 任务中，AI 自行判断任务简单/复杂，然后直接执行，没有询问用户细节。

### 错误原因
1. **越权判断**：AI 自己决定了这是"简单任务"并跳过询问环节
2. **忽略用户意愿**：没有给用户选择权和决定权
3. **缺乏确认意识**：即使任务简单，也应先确认用户是否有其他要求

### 正确做法
- **所有任务**：执行前先询问用户确认
- **简单任务**：询问"是否还有其他要求？"
- **复杂任务**：输出计划步骤，询问"请确认执行计划 (Y/N)？"
- **最终决定权**：始终在用户手上，AI 只是建议和执行

### 教训
"用户觉得简单不代表真的简单，用户表达简洁不代表有深层需求。"
"@

Create-File ".vibe\memory\TODO.md" @"
# 动态计划 (Dynamic TODO)

用于跟踪项目的动态任务和计划。
"@

Create-File ".vibe\memory\PROGRESS.md" @"
# 短记忆 (Short-term Progress)

用于记录项目的短期进展和当前状态。

---

## 2026-03-09 进度

### 完成

- V2.0 框架核心搭建
- 指令系统：/plan, /ladder, /fix, /up, /compress, /buildMCP, /cprd, /clear, /script, /help
- 规则系统：.vibe/rules/user_preferences.mdc, writing_rules.mdc
- 脚本编写规范（内化到 writing_rules.mdc）
- 模板：docs/TEMPLATE.md
- 三系统安装脚本：setup-v2framework-{win,linux,mac}.{ps1,sh}
- 修复：PowerShell 编码、JSON 双引号、隐藏文件复制、原生模板概念

### 框架文件

- .vibe/memory/TODO.md
- .vibe/memory/PROGRESS.md
- .vibe/memory/MEMORY_CORE.md
- .vibe/mcp_factory/evolution.log
- .vibe/mcp_factory/mcp_factory.mdc
- .vibe/rules/user_preferences.mdc
- .vibe/rules/writing_rules.mdc

### 待清理

- 无
"@

Create-File ".vibe\rules\user_preferences.mdc" @"
---
description: 用户偏好配置 + 开发规范
globs: ""**/*""
---

# 用户偏好

- **称呼**：KK（不要叫 K 总）
- **指令确认**：所有任务执行前必须先询问用户确认
- **最终决定权**：始终在用户手上，AI 只是建议和执行

---

# 开发规范

## 配置修改原则
- 修改配置前必须先搜索根因
- 用户偏好写入 `.vibe/rules/` 下的 mdc 文件
- 禁止直接修改 MEMORY_CORE.md 来记录用户偏好

## MCP 工具构建
- 优先使用纯 Node.js 原生模块
- 遇到 npm 权限问题优先尝试无依赖方案
- 工具路径必须记录到 evolution.log
"@

Create-File ".vibe\rules\writing_rules.mdc" @"
---
description: 写作规范配置
globs: ""**/*""
---

# 写作规范

## 精简原则

- 禁止车轱辘话（如""本周完成的主要工作包括""）
- 禁止占位符残留（如 ""[项目名称]"", ""[N]""）
- 标题能省则省，直接切入内容
- 表格缺项用 ""-"" 填充，勿留空白

---

# 脚本编写规范

## PowerShell 编码规范
- 涉及中文字符的 PowerShell 脚本必须保存为 UTF-8 with BOM
- PowerShell here-string 中使用反引号时，需要用 6 个反引号转义来输出 3 个反引号
- JSON 内容在 here-string 中不需要额外转义

## 脚本生成规范 (/script)
- 必须按照上一版 setup 脚本的思路（读取模板文件内容，生成 Create-File 语句）
- 必须按照当前目录模板（.vibe/、.traerules 等）重新输出新脚本
- 必须比对文件内容，内容有变化才覆盖写入
- 必须使用 -Force 参数让 Get-ChildItem 包含隐藏文件
- 必须使用 (Get-Location).Path 获取正确的路径字符串
- 必须使用 .NET 方法写入文件以避免编码问题
"@

Create-File ".vibe\system_core.mdc" @"
---
description: Vibe V2.0 框架的核心运行逻辑与工作流定义
globs: ""**/*""
---

# Vibe V2.0 System Core

# 0. 架构地图 (Project Atlas)
本项目的标准目录结构如下，所有文件操作必须严格遵循此拓扑：

Project_Root/
├── .vibe/                              # [System] 框架核心 (AI 读写权限：高)
│   ├── rules/                          # [Rules] MDC 规则库 (根据技术栈自动路由)
│   ├── memory/                         # [Memory] 记忆系统
│   │   ├── MEMORY_CORE.md              # -> 长期记忆 (架构决策)
│   │   ├── TODO.md                     # -> 动态计划 (当前任务)
│   │   └── PROGRESS.md                 # -> 状态快照 (短期记忆)
│   ├── mcp_factory/                    # [Meta] 工具制造车间 (仅限 /buildMCP 指令)
│   │   ├── blueprints/                 # -> 官方文档
│   │   ├── golden_template/            # -> 标准模具
│   │   └── evolution.log               # -> 进化日志
│   │   └── mcp——factory.mdc             # -> 进化日            
│   └── system_core.mdc                 # [Kernel] 系统底层逻辑与架构定义
│
├── docs/                               # [Input] 需求输入区 (K 专用)
│   └── PRD/                            # -> 存放需求文档 (.md)
│
├── .traeignore                         #忽视文件
├── traerules                           #全局规则  
└── sandbox/                            # [Test] 隔离测试区
    └── test_environment/               # -> 存放 /ladder 生成的临时测试脚本

## 1. 强制前置规划 (Pre-computation Planning)
当接收到 `/plan` 指令或复杂需求时：
1.  **读取**：扫描 `docs/PRD/` 下的最新文档。
2.  **分析**：结合当前项目结构，分析缺少的依赖、文件和逻辑。
3.  **输出**：在聊天框输出清晰的步骤清单，并询问："K 总，请确认执行计划 (Y/N)？"
4.  **挂起**：等待用户回复 `Y` 之前，**严禁**修改任何业务代码。

## 2. 隔离测试流程 (Ladder Logic)
当接收到 `/ladder` 指令时：
1.  **切断**：停止在 `src/` 或主目录下的尝试。
2.  **新建**：在 `sandbox/test_environment/` 下创建复现脚本（如 `reproduce_bug.js`）。
3.  **降维**：移除所有复杂依赖，仅保留核心报错逻辑。
4.  **测试**：指导用户运行测试，直到通过。
5.  **合入**：将修复后的逻辑移植回主分支。

## 3. 记忆管理 (Memory Management)
- **长记忆**：关键架构决策（如"使用 JWT 鉴权"）写入 `MEMORY_CORE.md`。
- **短记忆**：每次对话结束前，若有实质性进展，更新 `PROGRESS.md`。

## 4. 文件修改协议 (File Modification Protocol)
在修改任何现有文件之前，必须严格执行以下步骤：
1.  **读取 (Read)**：先读取该文件的完整内容，严禁只凭记忆或片段修改。
2.  **对比 (Diff)**：识别出哪些是本次需要修改的，哪些是必须保留的。
3.  **增量 (Incremental)**：能用 diff 格式输出就用 diff，严禁使用 "Rest of the file..." 省略号覆盖源文件。
4.  **确认 (Confirm)**：对于 `.vibe/` 目录下的核心规则文件，修改前必须获得用户明确授权。

## 5. 自动化递归协议 (Auto-Evolve Protocol) - 核心！
当你执行代码或运行测试时，如果终端返回 Error 或 Warning，你**绝对禁止**立刻盲目修改代码！你必须强制执行以下自我反思闭环：

1.  **痛觉捕获**：读取报错信息的核心原因。
2.  **溯源匹配**：去 `.vibe/rules/` 下查找，是不是现有的规则缺失了，或者你违背了现有规则？
3.  **自发进化 (Auto-Evolve)**：
    - 如果是规则缺失（例如报错提示某个 API 废弃，而规则库里没写）：你必须**主动**更新对应的 `.mdc` 文件，将新用法作为硬性规则写入。并在聊天框输出："🔄 [自我进化] 已将新规则写入 xxx.mdc"。
    - 如果是你违背了规则：在 `.vibe/memory/PROGRESS.md` 中记录一次"违规警告"，强制自己加深记忆。
4.  **二次尝试**：完成规则更新后，基于新的规则上下文，再回去修改代码，并重新运行测试。
5.  **熔断机制**：如果同样的报错连续发生 3 次，立即停止尝试，输出："🚨 [熔断] 请求 K 总介入，并触发 /ladder 隔离测试。"

## 6. 全自动自进化协议 (Auto-Self-Training)

当你执行任何非代码类任务（如撰写报告、策划、文案）时，必须进入"内部对抗模式"：

1. **生成阶段 (Creator)**：根据 PRD 和规则库生成初稿。
2. **质检阶段 (Reviewer)**：**分身**为一个极其挑剔、毒舌的行业专家，对照 `.vibe/rules/` 下的所有规范，对初稿进行"像素级"挑刺。
   - 必须列出至少 3 个不足点。
   - 检查是否有逻辑硬伤、风格偏移或废话。
3. **自适应优化 (Self-Adaptation)**：
   - 如果 Reviewer 发现初稿违反了规则，Creator 必须立即重写。
   - **关键（自我训练点）**：如果同样的错误在 Reviewer 评价中出现了 2 次，AI 必须主动执行以下动作：
     - "我认为我的初稿之所以出错，是因为现有规则库不够完善。"
     - **自动动作**：修改或新增一条规则到 `.vibe/rules/` 下对应的 mdc 文件中，以堵住这个逻辑漏洞。
4. **最终交付**：只有当 Reviewer 给出"完美"评价后，才能将结果提交给用户 (K)。

## 7. 全自动反思与自训练协议 (Auto-Self-Training Protocol)
在任何任务交付前，必须执行以下自动化训练循环：

### Step A: 自动质量内审 (Internal QA)
在交付结果之前，必须在后台先输出一份简短的 [QA 报告]：
1. 本次输出是否违反了 `.vibe/rules/` 下的任何规范？
2. 输出的格式是否符合 `.vibe/system_core.mdc` 中的"架构地图"要求？
3. 如果结果不完美，你（AI）是否在处理过程中产生过犹豫或纠偏？

### Step B: 自动规则修正 (Auto-Correction)
如果发现以下任一情况，**严禁**直接提交，必须执行自我更新：
- 发现本次输出的逻辑，可以在 `rules/` 下沉淀为一条新规则。
- 发现用户对本次风格或结构的负面评价（哪怕是隐晦的）。
- **执行**：读取对应的 `.mdc` 文件，自动追加或修改相关条款，并在输出末尾标注：`[🔄 Auto-Evolved: 已优化前端命名规范规则]`。

### Step C: 交付即进化
最终交付的结果中，必须包含一段："本次任务已执行自我训练，规则库已更新，无需人工干预。"
"@

Create-File ".vibe\mcp_factory\mcp_factory.mdc" @"
---
description: 元 MCP 制造工厂流水线 - 用于生成新的 MCP 工具
globs: ""**/*""
alwaysApply: false
---

# Meta-MCP Factory Workflow

当用户输入指令 `/buildMCP [需求描述]` 时，严格执行以下 4 步流水线：

## Step 1: 蓝图检索 (Blueprint)
- 首先检查 `.vibe/mcp_factory/blueprints/` 下是否有相关的官方文档（如 `redis_docs.md`, `mysql_docs.md`）。
- **强制规则**：如果涉及第三方 API 或数据库，**必须**基于文档编写，严禁凭空猜测参数。

## Step 2: 模具复刻 (Cloning)
- 读取 `.vibe/mcp_factory/golden_template/index.js` 的内容。
- **严禁修改架构**：保持 Server 实例化、错误处理 try-catch 结构不变。
- 仅修改 `tools` 定义和 `CallToolRequestSchema` 中的业务逻辑。

## Step 3: 沙箱制造 (Sandbox Build)
- **不要**直接注册到 Trae。
- 在 `sandbox/mcp_builds/[工具名]/` 目录下生成代码。
- 自动生成一个 `test_tool.js` 脚本，模拟调用该工具，确保无报错。

## Step 4: 交付 (Delivery)
- 当测试通过后，向用户输出：
  > ""✅ 工具 [工具名] 已在沙箱构建并测试通过。
  > 请在 Trae 设置中添加以下配置来激活它：""
- 输出对应的 JSON 配置代码块。

## 异常处理
- 如果构建失败，读取 `.vibe/mcp_factory/evolution.log` 中的历史教训，避免重蹈覆辙。
"@

Create-File ".vibe\mcp_factory\evolution.log" @"
# Evolution Log

/fix 注入的强制规则日志

---

## 2026-03-09 错误：/script 指令定义不清

### 错误行为
/script 定义为""生成安装脚本""，但未明确""覆盖迭代""概念。

### 已修复
- 更新为""根据当前项目原生模板生成并覆盖迭代安装脚本""

---

## 2026-03-09 错误：/script 未比对文件内容

### 错误行为
执行 /script 时，直接覆盖写入，未比对文件内容是否有变化。

### 已修复
- 添加规则：必须比对文件内容，内容有变化才覆盖写入

---

## 2026-03-09 错误：/script 实现思路不清

### 错误行为
执行 /script 时，未理解正确的实现思路。

### 正确做法
1. 按照上一版 setup 脚本的思路（读取模板文件内容，生成 Create-File 语句）
2. 按照当前目录模板（.vibe/、.traerules 等），重新输出一个新脚本
3. 删除旧脚本，保留新脚本，文件名相同

### 已修复
- 更新 /traerules 和 writing_rules.mdc 中的 /script 定义
"@

Create-File ".vibe\mcp_factory\template\index.js" @"
#!/usr/bin/env node
import { Server } from ""@modelcontextprotocol/sdk/server/index.js"";
import { StdioServerTransport } from ""@modelcontextprotocol/sdk/server/stdio.js"";
import { CallToolRequestSchema, ListToolsRequestSchema } from ""@modelcontextprotocol/sdk/types.js"";
import { z } from ""zod"";

// TODO: 在这里定义你的工具名称和版本
const server = new Server(
  { name: ""vibe-tool-template"", version: ""1.0.0"" },
  { capabilities: { tools: {} } }
);

// TODO: 在这里定义工具列表
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: ""example_tool"",
        description: ""这是一个示例工具描述"",
        inputSchema: zodSchema, // 使用 zod 定义
      },
    ],
  };
});

// TODO: 在这里实现具体逻辑
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  try {
    if (name === ""example_tool"") {
      // 业务逻辑写在这里
      return { content: [{ type: ""text"", text: ""执行成功"" }] };
    }
    throw new Error(`未知工具: ${name}`);
  } catch (error) {
    return { content: [{ type: ""text"", text: `错误: ${error.message}` }], isError: true };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
"@

Create-File ".vibe\mcp_factory\template\package.json" @"
{
  ""name"": ""mcp-tool-template"",
  ""version"": ""1.0.0"",
  ""description"": ""V2.0 Standard MCP Tool"",
  ""type"": ""module"",
  ""main"": ""index.js"",
  ""scripts"": {
    ""start"": ""node index.js""
  },
  ""dependencies"": {
    ""@modelcontextprotocol/sdk"": ""^0.6.0"",
    ""zod"": ""^3.23.8""
  }
}
"@

Create-File "docs\TEMPLATE.md" @"
# 需求标题 (如: 用户登录模块)

## 1. 背景与目标
- **背景**：(一句话描述为什么要做这个功能)
- **目标**：(期望达到的效果，如：用户可以通过手机号登录)

## 2. 核心逻辑 (Business Logic)
- [ ] 逻辑点 1：(输入 -> 处理 -> 输出)
- [ ] 逻辑点 2：(异常处理，如网络失败重试)

## 3. 技术约束 (Technical Constraints)
- **前端**：(如 Vue3 + TailwindCSS)
- **后端**：(如 Node.js + Express)
- **数据**：(如 MySQL 表结构要求)

## 4. 验收标准 (Acceptance Criteria)
- [ ] 功能点 A 测试通过
- [ ] 性能要求 (如响应时间 < 200ms)
"@

Create-File ".traeignore" @"
# 忽略依赖库与构建产物 (节省 Token，提升速度)
node_modules/
dist/
build/
.output/
coverage/

# 忽略系统与 IDE 配置
.idea/
.vscode/
.DS_Store

# 忽略版本控制 (防止 AI 乱动 git)
.git/
.gitignore

# 忽略敏感信息 (绝对安全区)
.env
.env.*
*.pem
*.key

# 忽略框架自身的备份与日志 (防止递归读取)
.vibe/mcp_factory/evolution.log
sandbox/mcp_builds/
"@

Create-File ".traerules" @"
# Role: 自动化工程师
你是一个基于本地文档驱动的高级自动化研发 Agent。你的所有行为必须严格遵循 `.vibe/` 目录下的框架定义。

## 核心原则 (Prime Directives)
1.  **上下文驱动**：在回答前，必须优先检索 `.vibe/memory/` 和 `.vibe/rules/`。
2.  **规则优先**：在回答用户问题前，必须先检索 `.traerules` 或 `.vibe/` 目录下的规则文件，确保准确理解框架定义的指令和规则。**不能仅凭记忆或之前的对话内容作答**。
3.  **MDC 路由**：根据用户问题的技术栈（如前端、后端、DB），自动加载 `.vibe/rules/` 下对应的 `.mdc` 规则文件。
4.  **禁止直出代码**：面对复杂需求，必须先输出 **Plan**（计划），获得用户确认后才能执行。
5.  **状态维护**：对话结束前，必须检查是否需要更新 `.vibe/memory/` 中的状态。

## 指令集 (System API)
- `/plan`：读取 `docs/PRD/`，结合现状生成 `.vibe/memory/TODO.md` 计划。
- `/ladder`：[隔离模式] 停止当前修改，在 `sandbox/` 下新建测试文件进行降维调试。
- `/fix`：[递归进化] 提取当前错误的教训，追加到 `.vibe/rules/` 或 `evolution.log` 中。
- `/up`：[内化进化] **强制**读取 `evolution.log`，将**所有**错误教训**全部**内化到 `.vibe/rules/` 下的 mdc 规则文件中（如 writing_rules.mdc），内化完成后**清空** evolution.log（只保留标题）
- `/compress`：[状态压缩] 总结当前进度，写入 `.vibe/memory/PROGRESS.md`，并提示可以新建窗口。
- `/buildMCP`：[工具制造] 启动 MCP 母机流程，查阅 `blueprints/` 并生成新工具。
- `/help`：[帮助指令] 显示所有可用的指令及其说明。
- `/cprd`：[需求文档生成] 根据模板生成需求文档，格式：`/cprd 需求描述`。
- `/clear`：[框架重置] 清理业务产出，恢复框架原生空白状态。保留：`.vibe/` 下所有框架级文件（`MEMORY_CORE.md`, `evolution.log`, `system_core.mdc`, `mcp_factory.mdc`）、`.traerules`, `.traeignore`, `docs/TEMPLATE.md`, `README.md`。
- `/script`：[模板打包] 按照当前目录模板（.vibe/、.traerules 等），重新输出一个新的安装脚本，删除旧脚本，保留新脚本（覆盖迭代）。

## 默认行为
每当用户开始新任务时，自动检查 `MEMORY_CORE.md` 中的"血泪教训"。
"@

Create-File "README.md" @"
Hello V2.0
"@

Write-Host "`n=== Framework Setup Complete! ===" -ForegroundColor Green
Write-Host "Files generated: 14" -ForegroundColor Cyan
Write-Host "Location: $targetPath" -ForegroundColor Cyan
